Feture/ajout des videos youtube aux cours
nyx-ei/Mood-NYX pull request #12
Opened 2024-08-08 02:30 UTC by karimalik

implementation de la fonctionnalité d'ajout de video youtube a un cours moodle

2024-08-09 16:01 UTC, SanAlexis requested changes
### Refactoring potentiel de la class auth.php
La classe a grossi et fait trop de choses. Elle est mûre pour un refactoring surtout des morceaux que tu as ajouté.

💡Quelques idées...

1. **Gestion des Connexions LDAP :**
   - Extraire les méthodes de gestion des connexions LDAP (`ldap_connect`, `ldap_close`, `test_dn`, etc.) dans une classe séparée appelée `LdapConnectionManager`.

2. **Gestion des Utilisateurs :**
   - Créer une classe `LdapUserManager` pour gérer toutes les opérations liées aux utilisateurs, telles que `user_login`, `user_create`, `get_userinfo`, `user_update_password`, etc.

3. **Gestion des Rôles :**
   - Extraire les méthodes de synchronisation des rôles (`sync_roles`, `is_role`, etc.) dans une classe `LdapRoleManager`.

4. **Configuration et Initialisation :**
   - Extraire la logique de configuration et d'initialisation dans une classe ou un service `LdapConfig` qui gère la configuration et la validation de LDAP.

5. **Tests et Diagnostics :**
   - Les méthodes liées aux tests de la configuration LDAP (`test_settings`, `ldap_test_settings`) pourraient être déplacées dans une classe `LdapTestService` ou similaire.

### Avantages du Refactoring:
- **Amélioration de la Maintenabilité :** Les classes plus petites et ciblées sont plus faciles à maintenir et à comprendre.
- **Meilleure Testabilité :** Chaque classe ou service peut être testé indépendamment, ce qui facilite l'écriture de tests unitaires.
- **Cohésion Améliorée :** Les méthodes au sein de chaque classe seront plus liées, améliorant ainsi la conception globale.

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/admin_ui.php
> +echo $OUTPUT->header();
Au lieu de multiplier les `echo` et rendre le code peu lisible, on peut procéder de cette façon.
```php
echo $OUTPUT->header();

$headerTitle = get_string('ad_group_role_mappings', 'auth_nyxei');
$currentMappings = s(get_config('auth_nyxei', 'ad_group_role_mappings'));
$saveButtonText = get_string('savechanges');

$html = <<<HTML
<h2>{$headerTitle}</h2>

<form method="post">
    <textarea name="ad_group_role_mappings" rows="10" cols="50">{$currentMappings}</textarea>
    <br><br>
    <input type="submit" value="{$saveButtonText}" class="btn btn-primary">
</form>
HTML;

echo $html;
echo $OUTPUT->footer();
```

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/auth.php
> -//TODO: Gestion des permissions d'utilisateur via AD
Pourquoi ?

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/auth.php
>          }
Est-ce une bonne idée de donner plus de détails sur le pourquoi de l'échec ou du moins sur la connexion qui n'arrive pas à se faire ?

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/auth.php
>              $this->failed_login_log($username, 'Invalid Credentials');
Est-ce que c'est la seule fois où tu as besoin de ce message ? Si non, il faut peut être ranger les messages dans une classe spécialisée que tout le monde peut utiliser.

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/auth.php
>          set_config('host', $config->host, 'auth_nyxei');
Constante ?

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/auth.php
>                      $user->auth = 'auth_nyxei';
Magic numbers.

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/auth.php
> +                if ($roleid) {
Existe-t-il une probabilité que les rôles coïncident entre AD et Moodle ?

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/auth.php
> +                    error_log("The Moodle role '$moodle_role' does not exist.");
Ce n'est pas un rôle Moodle, il faut trouver une autre dénomination pour ça.

2024-08-09 16:01 UTC, SanAlexis commented on auth/nyxei/classes/NotificationMessages.php
> +        'alert_message_login_failed' => "Alert: Multiple Failed Login Attempts",
Pourquoi tous les mots commencent par des majuscules ?

2024-08-09 16:01 UTC, SanAlexis commented on mod/youtubevideo/lib.php
> +function youtubevideo_delete_instance($id)
On peut améliorer le naming.

2024-08-09 16:01 UTC, SanAlexis commented on mod/youtubevideo/lib.php
> +function youtubevideo_update_instance($data, $mform)
Mauvais naming. C'est quoi `data` ? C'est quoi `mform` ?

2024-08-09 16:01 UTC, SanAlexis commented on mod/youtubevideo/lib.php
> +function youtubevideo_delete_instance($id)
Pour ma culture générale, c'est quoi l'explication derrière la structure du nom de cette méthode ?
@karimalik

2024-08-15 12:52 UTC, karimalik commented on auth/nyxei/auth.php
>          set_config('host', $config->host, 'auth_nyxei');
Non c'est pas une constante.

2024-08-16 01:16 UTC, karimalik commented on mod/youtubevideo/lib.php
> +function youtubevideo_update_instance($data, $mform)
$mform et $data est utilise pour manipuler les formulaires dans le contexte moodle.
$mform lui il est une instance de moodleform pour créer et gérer des formulaires. en gros lui il me permet d'ajouter des champs etc.. et $data lui il contient les données soumises.

2024-08-16 01:23 UTC, karimalik commented on mod/youtubevideo/lib.php
> +function youtubevideo_delete_instance($id)
bon ici la methode youtubevideo_delete_instance() elle permet de supprimer une instance de notre plugin youtubevideo, elle sera appelée lorsqu'une video youtube sera supprime du cours

2024-08-18 03:16 UTC, SanAlexis requested changes
## Considérations générales
Problème de nommage des méthodes et variables.
Quelques liens utiles:
1. [PSR1](https://www.php-fig.org/psr/psr-1/)
2. [PSR12](https://www.php-fig.org/psr/psr-12/)

2024-08-18 03:16 UTC, SanAlexis commented on mod/youtubevideo/lib.php
> +function youtubevideo_update_instance($data, $mform)
La question n'est pas sur leur utilité mais sur le choix des noms. Nommer une variable data est un énorme red flag 🚫.

2024-08-18 03:16 UTC, SanAlexis commented on mod/youtubevideo/lib.php
> +function youtubevideo_delete_instance($id)
Mais pourquoi la nommer comme ça ? C'est contre-intuitif.

2024-08-26 15:36 UTC, closed without merging