Feature/gestion videos youtube
nyx-ei/Mood-NYX pull request #23
Opened 2024-09-11 08:53 UTC by karimalik

Cette PR courvre la gestion des videos youtube par enseignant ainsi que l'optimisation du charge de la page de visualisation des videos par un user.

2024-09-15 15:02 UTC, SanAlexis requested changes
Beaucoup de courage !

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/lang/en/youtubevideo.php
> +// https://www.youtube.com/watch?v=yyUHQIec83I
Code mort.

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +    protected function definition()
`define` me semble un meilleur nom que `definition`.

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +                $mform->addElement('text', 'video_' . $video->id, $video->name, array('size' => '60'));
Comment on s'assure que les vidéos sont uniques et qu'on n'aura pas de doublons ?

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +        $videos = $DB->get_records('youtubevideo', array('course' => $COURSE->id));
Est-ce une bonne idée de collecter l'information directement de la BD ?

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +                $mform->addElement('text', 'video_' . $video->id, $video->name, array('size' => '60'));
Ici tu récupères l'URL ? Si oui, pourquoi ne pas récupérer l'url directement avec la possibilité de faire des validations dessus ? Le raw text est un peu difficile à gérer.

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +                    ));
### Traitement silencieux.
1. Que se passe-t-il si une ereur se produit pendant la mise à jour ?
2. Comment sait-on que la mise à jour s'est bien passée ?

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +            $id = substr($key, 6);
Il est possible que l'extraction ne produise pas de string. Il faut anticiper.
```php
if (!ctype_digit($id)) {
    continue; // Skip invalid IDs
}
```

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +        new moodle_url('/mod/youtubevideo/manage.php', array('id' => $course->id)),
* Que représente cette URL ?
* Pourquoi n'est pas une constante appelée dans le code ?

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/renderer.php
>      public function youtube_video($youtube_id)
Cet id a été sanitizé ?

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/renderer.php
> +    ");
Cette façon de faire de l'inline js est dangereuse et coûteuse à terme pour la maintenance.

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/renderer.php
> +    ");
Tu peux procéder comme ça.
```suggestion
define([], function() {
    return {
        init: function() {
            document.querySelectorAll('.youtubevideo-container').forEach(function(container) {
                container.addEventListener('click', function() {
                    var youtubeId = container.getAttribute('data-youtube-id');
                    var embedUrl = 'https://www.youtube-nocookie.com/embed/' + youtubeId + '?autoplay=1';
                    var iframe = document.createElement('iframe');
                    iframe.setAttribute('src', embedUrl);
                    iframe.setAttribute('frameborder', '0');
                    iframe.setAttribute('allow', 'autoplay; encrypted-media');
                    iframe.setAttribute('allowfullscreen', '');
                    iframe.style.width = '100%';
                    iframe.style.height = '100%';
                    container.innerHTML = '';
                    container.appendChild(iframe);
                });
            });
        }
    };
});
```

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/renderer.php
> +        $buttonContent = $this->get_icon('fa-cog') . ' ' . $this->get_string('manageyoutubevideos');
C'est du Font Awesome. C'est compatible avec Moodle ? Il me semble que Moodle utilise son propre système.

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/renderer.php
> +        $icon = html_writer::tag('i', '', ['class' => "fa $iconClass", 'aria-hidden' => 'true']);
Je soupçonne que `$this->output->container()` ou `$this->output->box()` sont plus intéressants que `html_writer` pour rester consistant avec l'approche Moodle.

2024-09-15 15:02 UTC, SanAlexis commented on mod/youtubevideo/renderer.php
> +    }
Est-ce que tu as vraiment besoin de créer ces fonctions ?
Un ⤵️
```suggestion
$button = $this->output->action_link($manageUrl, $buttonContent, null, ['class' => 'btn btn-primary youtubevideo-manage-btn']); 
```
aurait pu suffire.

2024-09-15 15:10 UTC, karimalik commented on mod/youtubevideo/lang/en/youtubevideo.php
> +// https://www.youtube.com/watch?v=yyUHQIec83I
Je ne comprend pas @SanAlexis tu peux être plus explicite 🙂

2024-09-15 15:17 UTC, karimalik commented on mod/youtubevideo/manage.php
> +    protected function definition()
Je crois que ce nom est propre à moodle pour la définition des form et la construction des forms. J'ai essayé d'utiliser une autre mais j'ai une erreur.

2024-09-15 15:19 UTC, karimalik commented on mod/youtubevideo/manage.php
> +        $videos = $DB->get_records('youtubevideo', array('course' => $COURSE->id));
Je pense que oui il me permet de récupérer facilement l'ID du cours courant ainsi me permet de récupérer la ou les vidéos correspondantes au cours.

2024-09-15 15:20 UTC, karimalik commented on mod/youtubevideo/manage.php
> +                $mform->addElement('text', 'video_' . $video->id, $video->name, array('size' => '60'));
C'est vrai que j'ai pas pensé à cela. Je vais gérer le cas où on peut avoir les doublons

2024-09-15 15:22 UTC, karimalik commented on mod/youtubevideo/manage.php
> +                    ));
Je pense que je genre cela. Dans le fichier de langue il y'a une clé pour l'affichage des messages etc...

2024-09-15 15:22 UTC, karimalik commented on mod/youtubevideo/manage.php
> +            $id = substr($key, 6);
D'accord

2024-09-15 15:23 UTC, karimalik commented on mod/youtubevideo/manage.php
> +        new moodle_url('/mod/youtubevideo/manage.php', array('id' => $course->id)),
Cet url représente l'URL qui mène vers la page de gestion des vidéos YouTubes associés au cours.

2024-09-15 15:24 UTC, karimalik commented on mod/youtubevideo/renderer.php
> +    ");
D'accord j'essaie ton idée.

2024-09-15 15:25 UTC, karimalik commented on mod/youtubevideo/renderer.php
> +        $buttonContent = $this->get_icon('fa-cog') . ' ' . $this->get_string('manageyoutubevideos');
Oui, c'est compatible avec moodle aussi

2024-09-15 15:26 UTC, karimalik commented on mod/youtubevideo/renderer.php
> +    }
J'ai créé ces functions pour rendre la function principale plus légère et facilité la maintenance

2024-09-15 15:40 UTC, karimalik commented
Merci 🙏

2024-09-16 01:18 UTC, SanAlexis commented on mod/youtubevideo/lang/en/youtubevideo.php
> +// https://www.youtube.com/watch?v=yyUHQIec83I
Ce commentaire est du code mort.

2024-09-16 01:19 UTC, SanAlexis commented on mod/youtubevideo/manage.php
> +        $videos = $DB->get_records('youtubevideo', array('course' => $COURSE->id));
Mais ne peut on pas le récupérer via l'API de Moodle pour interroger la BD ?

2024-09-16 01:20 UTC, SanAlexis commented on mod/youtubevideo/renderer.php
> +        $buttonContent = $this->get_icon('fa-cog') . ' ' . $this->get_string('manageyoutubevideos');
J'entends par compatible, le fait que `FA` et le _design system_ de Moodle se marient bien.

2024-09-20 04:08 UTC, merged